### ISSUE TITLE
Hi, this is support for vue 3??

### ISSUE THREAD

**Issue by kamaludin21** [vanderb/vue-tilt.js#14]

**Comment by PickleNik** [comment]
`app.use()`

**Comment by kamaludin21** [comment]
Get message 

`Could not find a declaration file for module 'vue-tilt.js'.`

**Comment by PickleNik** [comment]
nah, that message was aimed towards the owner of this repo, that's something he has to implement.
For now I'd just stick to [vanilla-tilt](https://www.npmjs.com/package/vanilla-tilt)

**Comment by vanderb** [comment]
Hi,

nope it was build on top of Vue2.
For now you have to use the vanilla-tilt and implement it on your own.

I will take a look to rebuild the package on Top of Vue3.
