### ISSUE TITLE
Error in directive tilt bind hook

### ISSUE THREAD

**Issue by AndrewGorman** [vanderb/vue-tilt.js#4]
Hi @vanderb 

Firstly, thank you so much for making this! I've used vanilla tilt in previous (non-vue) projects and always loved it.

Unfortunately I'm getting these console errors when I attempt to use the v-tilt directive on an element. Any idea what could be causing this?

```Error in directive tilt bind hook: "TypeError: vanilla_tilt__WEBPACK_IMPORTED_MODULE_0__.VanillaTilt is undefined"```

```TypeError: "vanilla_tilt__WEBPACK_IMPORTED_MODULE_0__.VanillaTilt is undefined"```

I thought it may be that vanilla-tilt is also required as a dependency so I added it, but that didn't seem to resolve the issue.

I'd really appreciate any ideas you have! Thanks again for this!

**Comment by vanderb** [comment]
Hi @AndrewGorman ,

sorry for hearing that. This could be an issue in the build process.
I rebuild the files and published them to version 1.1.1.

Can you update to that version and tell, if this error is gone now?

Thank you!

**Comment by AndrewGorman** [comment]
That did it!

Wow, it was so easy to add and get working! 

Seriously, thank you so much for this wrapper, I love it! #starred

**Comment by vanderb** [comment]
@AndrewGorman 
Great! 👍 
If you find any issues please let me know.
Cheers
