### ISSUE TITLE
How to use it with Nuxt ?

### ISSUE THREAD

**Issue by MatteoGauthier** [vanderb/vue-tilt.js#6]

**Comment by MatteoGauthier** [comment]
I have the answer, simply add a `~/plugins/tilt.js` file with the imports :
```
import Vue from "vue";
import VueTilt from 'vue-tilt.js'
Vue.use(VueTilt)
```

then add to your html template the v-tilt attribute

```
<img v-tilt src="http://via.placeholder.com/500x300" alt />
```

**Comment by vanderb** [comment]
@MattixNow Nice 👍
Good to see, that you've found a solution.
